import { useRouter } from "next/router";
import { Card, Text } from "@nextui-org/react";
import { Input } from "@nextui-org/react";
import { Button } from "@nextui-org/react";
import { FiPower } from "react-icons/fi";
import React, { useContext, useState } from "react";
import Head from "next/head";
import { GlobalService } from "../../api/services/GlobalService";
const service = new GlobalService();
import toast from 'react-hot-toast';
import { context } from "../context/providerSpinner";


export const Login = () => {
  const [values, setValues] = useState({ username: "", password: "" });
  const { setState }: any = useContext(context);
  const router = useRouter();



  const login = (e: any) => {
    e.preventDefault();
    document.cookie = "token=true";
    setState(true);
    service.login(values.username, values.password).subscribe((res: any) => {
      setState(false);
      if (res.DataBeanProperties.ObjectValue) {
        sessionStorage.setItem("user", JSON.stringify(res.DataBeanProperties.ObjectValue.DataBeanProperties.Account.DataBeanProperties))
        document.cookie = "token=true";
        setValues({ username: "", password: "" });
        router.push("/dashboard");
      } else {
        toast.error("usuario o contraseña incorrecto");
      }
    })
  };

  return (
    <>
      <Head>
        <title>API - AMC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* LOGIN */}

      <Card css={{ width: "500px", backgroundColor: "white", padding: "40px" }}>


        <form style={{ textAlign: "center" }} onSubmit={login}>

          <Text h1 size={30} css={{ textGradient: "220.55deg, #FFD439 0%, #FF7A00 90%" }} className="login__titulo" >
            Iniciar Sesión
          </Text>
          <Input
            css={{ marginTop: "50px", width: "100%", fontFamily: "Questrial" }}
            color="warning"
            size="lg"
            bordered
            labelPlaceholder="Usuario"
            value={values.username}
            onChange={(e: any) => { setValues({ ...values, username: e.target.value }) }}
          />


          <Input.Password
            bordered
            color="warning"
            css={{ marginTop: "40px", border: "none", width: "100%", fontFamily: "Questrial" }}
            size="lg"
            labelPlaceholder="Contraseña"
            value={values.password}
            onChange={(e: any) => { setValues({ ...values, password: e.target.value }) }}
          />

          <Button type="submit" shadow size={'lg'} iconRight={<FiPower />} color="warning" css={{ fontFamily: "Questrial", fontSize: "20px", display: "block", marginTop: "40px", width: "100%" }} >
            Ingresar
          </Button>

        </form>


      </Card>

    </>
  );
};
